### ISSUE TITLE
[BUG] Professors can't edit async questions 

### ISSUE THREAD

**Issue by wskksw** [ubco-db/helpme#36]
**Describe the bug**
Professors can't edit async questions 

**To Reproduce**

Have an account with a student role in course 2 and a professor role in course 1.
Attempt to edit async questions in course 1 as a professor.
Observe that the edit operation fails.

**Expected behavior**
Being able to edit async questions as professors in course 1

**Current behavior**
Can't edit course 1, because it's not searching for role in course.

<img width="459" alt="image" src="https://github.com/user-attachments/assets/3416d917-9f4d-4002-a2ae-5c7f51106069">

**Screenshots**

**Additional context**

**Comment by AdamFipke** [comment]
this was fixed a while ago, just cleaning up issues board
